---

- name: Run cfg commands on routers
  hosts: 192.168.100.1

  tasks:

    - name: Config QoS policy
      ios_config:
        parents:
          - "interface Ethernet0/{{item}}"
        lines:
          - ip mtu 1300
      with_items:
        - 1
        - 2
        - 3
